### ISSUE TITLE
Mark DenoiseState as Send

### ISSUE THREAD

**Issue by Flakebi** [RustAudio/rnnoise-c#8]
Currently, a `DenoiseState` cannot be sent between threads.
I’m not perfectly sure what the preconditions are to mark something as `Send`. Looking at the C source code, it seems like the state struct only contains buffers and there is no global state or anything other that would prevent it from being used in other threads, so I think marking `DenoiseState` as `Send` is fine.

**Comment by est31** [comment]
Yeah there shouldn't be any global state. PRs welcome!
